{ pkgs, pkgs-unstable, config, ...}:
{
	#NOTE: This module was created for the old stable nixos configuration, fix it before wanting to use it.
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    systemd.enable = true;

    settings = {
      input = {
        kb_layout = "latam";
      };

      cursor = {
        inactive_timeout = 2.0;
      };

      env = [
        "HYPRCURSOR_THEME, Bibata-Modern-Ice"
        "HYPRCURSOR_SIZE, 30"
      ];
      autogenerated = 0;
      "monitor" = ",preferred,auto,1";

      general = {
        gaps_in = 0;
        gaps_out = 0;
        border_size = 4;

        #"col.active_border" = "rgb(75fdff) rgb(75fdff) 150deg";
        #"col.inactive_border" = "rgb(293036) rgb(293036) 150deg";

        layout = "master";
      };

      master = {
        new_on_top = true;
        mfact = "0.60";
      };

      decoration = {
        rounding = 0;
        inactive_opacity = 0.6;
        active_opacity = 1;
        fullscreen_opacity = 1;

        blur = {
          enabled = true;
          size = 10;
          passes = 2;
          new_optimizations = true;
        };
      };

      animations = {
        enabled = true;
        bezier = "myBezier, 0.32, 0, 0.67, 0";

        animation = [
          "windowsIn, 1, 2, myBezier, popin 80%"
          "windowsOut, 1, 2, myBezier, popin 80%"
          "layers, 1, 2, myBezier, popin 70%"
          "fadeIn, 1, 5, myBezier"
          "fadeOut, 1, 5, myBezier"
          "workspacesIn, 1, 2, myBezier, slidefade 30%"
          "workspacesOut, 1, 2, myBezier, slidefade 30%"
          "border, 1, 2, myBezier"
        ];
      };

      "$mainMod" = "Alt";
      "bind" = [
        "$mainMod, U, exec, alacritty"
        "$mainMod, Y, killactive"
        "$mainMod, T, togglefloating"
        "$mainMod, space, exec, rofi -show drun"
        "$mainMod, N, exec, wlogout -b 1 -c 20 -r 20 -L 1700 -T 325 -B 325"
        "$mainMod, 9, exec, hyprpicker"
        "$mainMod, 8, exec, grim"
        "SUPER, F, fullscreen"
        "SUPER, Q, exit"

        "$mainMod, H, movefocus, l"
        "$mainMod, L, movefocus, r"
        "$mainMod, K, movefocus, u"
        "$mainMod, J, movefocus, d"

        "$mainMod, I, workspace, -1"
        "$mainMod, O, workspace, +1"

        "SUPER, I, movetoworkspace, -1"
        "SUPER, O, movetoworkspace,+1"

        "$mainMod, P, layoutmsg, swapwithmaster"
        "$mainMod, M, layoutmsg, cyclenext"
        "$mainMod, V, layoutmsg, mfact -0.05"
        "$mainMod, B, layoutmsg, mfact +0.05"

        "SUPER, 1, exec, hyprctl dispatch setprop activewindow alpha 0.1"
        "SUPER, 2, exec, hyprctl dispatch setprop activewindow alpha 0.2"
        "SUPER, 3, exec, hyprctl dispatch setprop activewindow alpha 0.3"
        "SUPER, 4, exec, hyprctl dispatch setprop activewindow alpha 0.4"
        "SUPER, 5, exec, hyprctl dispatch setprop activewindow alpha 0.5"
        "SUPER, 6, exec, hyprctl dispatch setprop activewindow alpha 0.6"
        "SUPER, 7, exec, hyprctl dispatch setprop activewindow alpha 0.7"
        "SUPER, 8, exec, hyprctl dispatch setprop activewindow alpha 0.8"
        "SUPER, 9, exec, hyprctl dispatch setprop activewindow alpha 0.9"
        "SUPER, 0, exec, hyprctl dispatch setprop activewindow alpha 1"
      ];

      "bindm" = [
        "SUPER, mouse:272, movewindow"
        "SUPER, mouse:273, resizewindow"
      ];

      exec-once = [
        "waybar"
      ];
        
    };
  };
}
