{ pkgs, config, ... }:
{
  imports = [
    # Autogenerated hardware config
    /etc/nixos/hardware-configuration.nix

    # General system configurations
    ./modules/systemSettings.nix

    # system wide packages
    ./modules/systemPackages.nix

    # Fonts
    ./modules/fonts.nix

    # System services
    ./modules/systemServices.nix

    # System programs
    ./modules/systemPrograms.nix

    # login configuration
    ./modules/login.nix

    # Stylix configuration
    ./modules/stylix.nix
  ];
}
